const UserList = [
  {
    id: 1,
    name: "Hayward",
    username: "hszepe0",
    age: 31,
    nationality: "norway",
    friends: [
      {
        id: 6,
        name: "Fulton",
        username: "fbuckner5",
        age: 55,
        nationality: "Ukraine",
      },
    ],
  },
  {
    id: 2,
    name: "Bree",
    username: "bpolhill1",
    age: 78,
    nationality: "ecuador",
    friends: [
      {
        id: 7,
        name: "Alta",
        username: "aleffek6",
        age: 78,
        nationality: "France",
      },
      {
        id: 8,
        name: "Curtis",
        username: "cmcalroy7",
        age: 58,
        nationality: "Indonesia",
      },
    ],
  },
  {
    id: 3,
    name: "Verine",
    username: "vmellenby2",
    age: 32,
    nationality: "sweden",
    friends: [
      {
        id: 11,
        name: "Guglielma",
        username: "glomba",
        age: 96,
        nationality: "Japan",
      },
      {
        id: 14,
        name: "Gaby",
        username: "gmurphyd",
        age: 53,
        nationality: "china",
      },
      {
        id: 15,
        name: "Ingeberg",
        username: "iigglesdene",
        age: 59,
        nationality: "Indonesia",
      },
      {
        id: 16,
        name: "Dale",
        username: "dburstowef",
        age: 43,
        nationality: "China",
      },
    ],
  },
  {
    id: 4,
    name: "Ronny",
    username: "rhaddleston3",
    age: 55,
    nationality: "China",
    friends: [
      {
        id: 9,
        name: "Garfield",
        username: "ghidderley8",
        age: 68,
        nationality: "Nigeria",
      },
      {
        id: 10,
        name: "Doralin",
        username: "ddudman9",
        age: 71,
        nationality: "Colombia",
      },
    ],
  },
  {
    id: 5,
    name: "Cissy",
    username: "ccalfe4",
    age: 60,
    nationality: "bulgaria",
    friends: [
      {
        id: 12,
        name: "Ty",
        username: "trivittb",
        age: 18,
        nationality: "Russia",
      },
      {
        id: 13,
        name: "Cairistiona",
        username: "chumphriesc",
        age: 99,
        nationality: "Syria",
      },
    ],
  },
];

const MovieList = [
  {
    id: 1,
    name: "Freejack",
    yearOfPublish: 1992,
    isInTheater: false,
  },
  {
    id: 2,
    name: "Fearless Freaks, The",
    yearOfPublish: 1995,
    isInTheater: false,
  },
  {
    id: 3,
    name: "Bloody Birthday",
    yearOfPublish: 1994,
    isInTheater: false,
  },
  {
    id: 4,
    name: "It's All About Love",
    yearOfPublish: 2012,
    isInTheater: true,
  },
  {
    id: 5,
    name: "Jane Eyre",
    yearOfPublish: 2005,
    isInTheater: true,
  },
  {
    id: 6,
    name: "Waking Madison ",
    yearOfPublish: 1993,
    isInTheater: true,
  },
  {
    id: 7,
    name: "Fly Me to the Moon",
    yearOfPublish: 2007,
    isInTheater: true,
  },
  {
    id: 8,
    name: "Campaign, The",
    yearOfPublish: 2005,
    isInTheater: true,
  },
  {
    id: 9,
    name: "The Second Best Exotic Marigold Hotel",
    yearOfPublish: 2005,
    isInTheater: true,
  },
  {
    id: 10,
    name: "Ticking Clock",
    yearOfPublish: 2007,
    isInTheater: false,
  },
  {
    id: 11,
    name: "8 Diagram Pole Fighter, The (a.k.a. Invincible Pole Fighter) (Wu Lang ba gua gun)",
    yearOfPublish: 2011,
    isInTheater: false,
  },
  {
    id: 12,
    name: "Australian Atomic Confessions",
    yearOfPublish: 2011,
    isInTheater: false,
  },
  {
    id: 13,
    name: "Crac",
    yearOfPublish: 2008,
    isInTheater: false,
  },
  {
    id: 14,
    name: "Time of Your Life, The",
    yearOfPublish: 1994,
    isInTheater: true,
  },
  {
    id: 15,
    name: "Born to Kill",
    yearOfPublish: 2009,
    isInTheater: true,
  },
  {
    id: 16,
    name: "Sunflower (Xiang ri kui)",
    yearOfPublish: 1999,
    isInTheater: false,
  },
  {
    id: 17,
    name: "Mesmerist, The",
    yearOfPublish: 2010,
    isInTheater: true,
  },
  {
    id: 18,
    name: "Aurora Borealis",
    yearOfPublish: 2003,
    isInTheater: false,
  },
  {
    id: 19,
    name: "Skyscraper Souls",
    yearOfPublish: 2008,
    isInTheater: false,
  },
  {
    id: 20,
    name: "Three Fugitives",
    yearOfPublish: 1993,
    isInTheater: false,
  },
];
module.exports = { UserList, MovieList };
